options(warn=-1)
suppressPackageStartupMessages(library(affy))
opt = read.delim(file="options.mi", sep="\t", header=F)
opt=as.vector(as.matrix(opt))
setwd("Cel Files")
rawdata = ReadAffy()
norm = suppressMessages(expresso(rawdata, bgcorrect.method=opt[1],normalize.method=opt[2],pmcorrect.method=opt[3],summary.method=opt[4]))
e = exprs(norm)
e2 = cbind(rownames(e),e)
e3 = rbind(c("Probeset ID",colnames(e)),e2)
setwd("../")
write(file="norm.txt", paste("### Date: ", Sys.time(),sep=""),append=F)
write(file="norm.txt", paste("### Background Correction Method:",opt[1]),append=T)
write(file="norm.txt", paste("### Normalization Method:",opt[2]),append=T)
write(file="norm.txt", paste("### PM Correction Method:",opt[3]),append=T)
write(file="norm.txt", paste("### Summarization Method:",opt[4]),append=T)
write(file="norm.txt", "",append=T)
write(file="norm.txt", t(e3), ncol=ncol(e3), sep="\t",append=T)
options(warn=0)
